dist: trusty
sudo: true
language: python

python:
  - 3.5

branches:
    only:
        - master

env:
  matrix:
    - python=3.5 CONDA_PY=35 OPENEYE_CHANNEL="https://pypi.anaconda.org/OpenEye/simple"

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="oeommtools"
    - VERSION="0.0.2"
    - OE_LICENSE="$HOME/oe_license.txt"
    - DEV_TOOLS="devtools/conda-recipe"
    - PKG_NAME="oeommtools"
    - USER="OpenEye"
    - OS=$TRAVIS_OS_NAME-64

before_install:
  - openssl aes-256-cbc -K $encrypted_b67118b96bf1_key -iv $encrypted_b67118b96bf1_iv -in oe_license.txt.enc -out oe_license.txt -d
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes true --set changeps1 no
  - conda update --yes -q conda
  - conda install conda-build
  - conda install anaconda-client
  - conda info -a

install:
  - conda create -n openeye python=$python
  - source activate openeye
  - pip install -i ${OPENEYE_CHANNEL} openeye-toolkits-python3-ubuntu-14.04-x64 && python -c "import openeye; print(openeye.__version__)"
  - conda config --add channels ${ORGNAME}
  - conda build --python $python ${DEV_TOOLS}
  - conda install --use-local ${PACKAGENAME}
  - conda list

script:
  - py.test -s -v tests

after_success:
  - source deactivate
  - anaconda -t $CONDA_UPLOAD_TOKEN remove --force $USER/$PKG_NAME/$VERSION
  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l Orion $HOME/miniconda/conda-bld/$OS/$PKG_NAME-*.tar.bz2 --force
  - conda convert -p osx-64 $HOME/miniconda/conda-bld/$OS/$PKG_NAME-*.tar.bz2
  - anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l Orion osx-64/$PKG_NAME-*.tar.bz2 --force