dist: trusty
sudo: false
language: python

python:
- 3.5

branches:
    only:
        - master

env:
  matrix:
    - CONDA_PY=35  OPENEYE_CHANNEL="-i https://pypi.anaconda.org/openeye/channel/main/simple"
  global:
    - ORGNAME="omnia"
    - OE_LICENSE="$HOME/oe_license.txt"

before_install:
- openssl aes-256-cbc -K $encrypted_b67118b96bf1_key -iv $encrypted_b67118b96bf1_iv -in oe_license.txt.enc -out oe_license.txt -d
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes true --set changeps1 no
- conda update --yes -q conda
- conda info -a

install:
- pip install -i https://pypi.anaconda.org/OpenEye/simple OpenEye-toolkits

script:
# Add omnia channel
- conda config --add channels ${ORGNAME}
# Build conda dev package
- conda build devtools/conda-recipe
# Create and activate openeye environment
- conda create --yes -n openeye python=$python
- source activate openeye
# Test
#- py.test -v -s tests




