package:
  name: oeommtools
  version: {{ environ['VERSION'] }}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - pytest
    - setuptools
    - numpy
    - numpydoc
    - openmm
  run:
    - python
    - pytest
    - setuptools
    - numpy
    - numpydoc
    - openmm
