package:
  name: oeommtools
  version: {{ environ['VERSION'] }}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - pytest
    - setuptools
    - numpy
    - numpydoc
    - openmm
    - pyparsing
  run:
    - python
    - pytest
    - setuptools
    - numpy
    - numpydoc
    - openmm
    - pyparsing

test:
  requires:
    - pytest
  imports:
    - oeommtools

about:
  home: https://github.com/oess/oeommtools