package:
  name: oeommtools
  version: '1.1.22b0'

source:
  path: ../../

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  string: py_0

requirements:
  build:
    - python
    - pytest
    - setuptools
    - numpy
    - openmm
    - pyparsing
    - packmol
    - parmed
  run:
    - python
    - pytest
    - setuptools
    - numpy
    - openmm
    - pyparsing
    - packmol
    - parmed

test:
  requires:
    - pytest
  imports:
    - oeommtools

about:
  home: https://github.com/oess/oeommtools
  license: OpenEye proprietary
  summary: OpenEye and OpenMM utilities